### ISSUE TITLE
Incorrect IP CRTL+C Given

### ISSUE THREAD

**Issue by Powboyj** [online-mc/online-mc.github.io#5]
### ⠀

When clicking on the Asianf4rmer SMP IP button, you instead get "wss://legxndsmp.minecraft.pe"
Should be a simple fix, just correct the IP in the CRTL+C box
<img width="735" alt="Screenshot 2024-01-21 205826" src="https://github.com/online-mc/online-mc.github.io/assets/59149634/f7476040-59e1-49b4-8a21-ee026ec4d971">

**Comment by radmanplays** [comment]
fixed in https://github.com/online-mc/online-mc.github.io/commit/9807bff4a582c26f1aef13426b0ddc86e8376371
